# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  
  lane :beta do
  # ...
    build_app
    crashlytics(api_token: "79dc023bea5dcecc8b1e1744b71570c00b9b3a50",
             build_secret: "9b76996460e2e25fda2299ca6617a123579e2a8c1a00ca36a4bd007f3966ab22")
  end

end
